# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the sample median using optimized C++ code
#'
#' @param x numeric vector.
#' @export
#' @return Sample median of x after removing NA values.
med <- function(x) {
    .Call(`_fastmedian_med`, x)
}

